### PR TITLE
update ethereumjs-block and merkle-patricia-tree

### PR DESCRIPTION
**Pull request by ujjwalgupta94**
* update ethereumjs-block to @ethereumjs/block
* update merkel-patricia-tree to latest version
* rm unused package
* some related changes due to package update

### CODE REVIEW

**Comment by andrewkmin** [comment]
thanks for the progress here. i would like to contribute, but just don't have much context at the moment. however, i did try to set up a local dev environment and ran into some issues, even on master. i'm using node v12 on macOS, and during the `npm run debug` step, i'm seeing an error:
```
Error: Unknown arguments format passed to new HDWalletProvider. Please check your configuration and try again
```

**Comment by ujjwalgupta94** [comment]
@andrewkmin have just added `env.example`, you need to create `.env` file with same format as example one and add the value .

**Comment by ujjwalgupta94** [comment]
this has been completed, its under review.

**Comment by andrewkmin** [comment]
> this has been completed, its under review.

thank you! i'm seeing some CI tests failing; fwiw, it looks like those same tests are failing when running the suite off master locally as well

**Comment by ujjwalgupta94** [comment]
all tests are OK now, it was actually some changes needed from maicjs-ethers. I had locally changed and was able to make it run 😛 .

**Comment by andrewkmin** [comment]
any update on when this might be reviewed? thanks again 🙏

**Comment by ujjwalgupta94** [comment]
@andrewkmin will take this week, this is affecting proof logic so gotta test different withdrawals.

**Comment by ujjwalgupta94** [comment]
@andrewkmin i have released this with beta flag. You can install it using - 

```
npm i @maticnetwork/maticjs@beta
```

Let me know if you found any issue.

**Pull request merged**
