### PR TITLE
feat: add rootChainDefaultBlock for checkpoint read

### PR DESCRIPTION
**Pull request by clarkchen**
Now: getLastChildBlock is fixed to read only after finilized state is confirmed.

Feat: Add config option rootChainDefaultBlock (default finilized)

### CODE REVIEW

**Comment by clarkchen** [comment]
@ujjwalgupta94 , please review on this pull request

**Review by ujjwalgupta94 — APPROVED** [review]
Looks good to me @py-zoid

**Comment by clarkchen** [comment]
@py-zoid , plz have a review on this pr, thx~

**Comment by clarkchen** [comment]
rebase latest

**Review by py-zoid — APPROVED** [review]
Extremely sorry for the delay guys. This LGTM!

**Comment by clarkchen** [comment]
@ujjwalgupta94 , hello, what else should I do after the code review ?

**Comment by ujjwalgupta94** [comment]
extremely sorry @clarkchen, let me reach out to team.

**Comment by ujjwalgupta94** [comment]
@clarkchen your changes are available on - `3.6.0-beta.1` with beta flag. We will do another release as main release (without beta) after holiday. 

```
@maticnetwork/maticjs@3.6.0-beta.1
```

**Pull request merged**
